#TASK1
#import collections 

#Person = collections.namedtuple('Person', ['first_name', 'last_name', 'age', 'birth_place', 'post_index'])

#person = Person('Maks', 'Lazoryk', 18, 'Lviv', '01146')

#print(person.first_name)

#print(person.last_name)
#print(person.age)
#print(person.birth_place)
#print(person.post_index)


#TASK2
import collections

Cat = collections.namedtuple('Cat',['nickname','age','owner'])

cat = Cat('Mafia', 4, 'Robert')

